import = [
    # "~/.config/alacritty/themes/themes/atom_one_light.toml",
    # "~/.config/alacritty/themes/themes/catppuccin_latte.toml",
    "~/.config/alacritty/themes/themes/gruvbox_light.toml",
    "~/.config/alacritty/alacritty.toml"
]
