import = [
# "~/.config/alacritty/themes/themes/atom_one_light.toml"
]

[font]
size = 16.0

[font.bold]
family = "Hasklug Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hasklug Nerd Font Mono"
style = "BoldItalic"

[font.italic]
family = "Hasklug Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hasklug Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[scrolling]
history = 20000

