[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "BoldItalic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

#[window]
#opacity = 0.7

[window.padding]
x = 5
y = 5

[scrolling]
history = 20000
