#import = [
#"~/.config/alacritty/themes/themes/atom_one_light.toml"
#]

[ env ]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

#[window]
#opacity = 0.7

[window.padding]
x = 5
y = 5

[scrolling]
history = 20000
