[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
    # "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
    # "~/.config/alacritty/themes/themes/ayu_dark.toml",
    # "~/.config/alacritty/themes/themes/github_dark_default.toml",
    # "~/.config/alacritty/themes/themes/tokyo-night.toml",
    "~/.config/alacritty/alacritty.toml"
]
