name = "Proton"
performance_mode = true
scx_sched = lavd
scx_sched_props = gaming
start_script = "lact cli profile set performance"
stop_script = "lact cli profile set efficiency"
idle_inhibit = true
