#!/bin/sh

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

fancy_echo "Updating Homebrew formulae ..."
brew update --force # https://github.com/Homebrew/brew/issues/1151

if [ "$WITH_ASDF_PYTHON" = 'no' ]; then
  brew install python
fi
if [ "$WITH_ASDF_GO" = 'no' ]; then
  mkdir -p "$HOME"/code/go/{bin,pkg,src}
  brew install go
fi
if [ "$WITH_ASDF_ruby" = 'no' ]; then
#  brew install ruby
#  export PATH="/usr/local/opt/ruby/bin:$PATH"
  sudo gem install neovim
  sudo gem install solargraph
  # sudo gem install tmuxinator
fi

brew bundle --file=~/dotfiles/Brewfile

if command -v /Applications/iTerm.app/Contents/MacOS/iTerm2 >/dev/null; then
  fancy_echo "Setup sync for iTerm2 Prefs in a custom folder ..."
  killall cfprefsd # This will get rid of cached settings
  # Specify the preferences directory
  defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "$HOME/.dotfiles/iterm2"
  # Tell iTerm2 to use the custom preferences in the directory
  defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
fi

