[custom]
# Apply the 'performance' profile when a game starts
start=lact cli profile set performance && powerprofilesctl set performance

# Revert to the 'efficiency' profile when the game closes
end=lact cli profile set efficiency && powerprofilesctl set power-saver
