#!/usr/bin/env bash
# For this to work you need:
# 'gnome-pomodoro-git' and 'pipx install i3-gnome-pomodoro'
# https://github.com/kantord/i3-gnome-pomodoro

pomodoro=$(i3-gnome-pomodoro status)
echo $pomodoro
