#!/bin/sh

current_lang=$(setxkbmap -print | awk -F"+" '/xkb_symbols/ {print $2}')

if [ $current_lang = 'us' ]; then
  setxkbmap gr
  notify-send "Keyboard Layout" "Changed to Greek 🇬🇷"
fi

if [ $current_lang = 'gr' ]; then
  setxkbmap us
  notify-send "Keyboard Layout" "Changed to English 🇺🇸"
fi
