#!/usr/bin/env bash
I3_CONFIG=$HOME/.config/i3/config
I3_BAR=$HOME/.config/i3/config.d/bar.conf
mod_key=$(sed -nre 's/^set \$mod (.*)/\1/p' ${I3_CONFIG})
{
    grep "^bindsym" ${I3_CONFIG}
    grep "^bindsym" ${I3_BAR}
} |
    sed "s/-\(-\w\+\)\+//g;s/\$mod/${mod_key}/g;s/Mod1/Alt/g;s/exec //;s/bindsym //;s/^\s\+//;s/^\([^ ]\+\) \(.\+\)$/\2: \1/;s/^\s\+//" |
    tr -s ' ' |
    rofi -dmenu -p "Keyhint" -config ~/.config/rofi/rofikeyhint.rasi
