#!/bin/sh
# Supports both ubuntu and EndeavourOS
# NOTE: It is needed even on single monitor setup, because virtmon breaks otherwise

# rx580
# SINGLE_MONITOR=DisplayPort-1
# igpu (rx580 pass-through)
# SINGLE_MONITOR=DisplayPort-0
# igpu
# SINGLE_MONITOR=DisplayPort-2

# Find the first connected monitor
CONNECTED_MONITOR=$(xrandr --query | grep ' connected' | head -n 1 | awk '{print $1}')

if [ -z "$CONNECTED_MONITOR" ]; then
    echo "No connected monitor found."
    exit 1
fi

echo "Found connected monitor: $CONNECTED_MONITOR"

# Check if running in a VM or if hostname is "hades", ThinkPad Laptop
if [ "$(hostname)" = "hades" ] || systemd-detect-virt -q; then
    echo "Running in a VM or on host 'hades', setting resolution to 1920x1080."
    xrandr --output "$CONNECTED_MONITOR" --primary --mode 1920x1080 --pos 0x0 --rotate normal
else
    echo "Running on main desktop, setting resolution to 5120x1440."
    xrandr --output "$CONNECTED_MONITOR" --primary --mode 5120x1440 --pos 0x0 --rotate normal
fi
