#!/usr/bin/env bash
#
# Use rofi to change power profiles using systemd power-profiles-daemon.
# This script is intended to be launched via a keybinding (e.g., in i3).

# Rofi options
ROFI_THEME=(-theme ~/.config/rofi/power-profiles.rasi)
ROFI_PROMPT_TEXT="Power Profile"

# Check whether a command exists
function command_exists() {
  command -v "$1" &> /dev/null 2>&1
}

# Ensure rofi, and powerprofilesctl are available
if ! command_exists rofi || ! command_exists powerprofilesctl; then
  echo "Error: rofi, powerprofilesctl command not found." >&2
  command_exists notify-send && notify-send -u critical "Power Profiles Menu Error" "Missing dependencies: rofi, or powerprofilesctl"
  exit 1
fi

# menu defined as an associative array
typeset -A menu

# Menu with keys/commands
menu=(
  [  Performance]="powerprofilesctl set performance"
  [  Balanced]="powerprofilesctl set balanced"
  [  Power Saver]="powerprofilesctl set power-saver"
)

menu_nrows=${#menu[@]}

# Prepare rofi options
rofi_options=(-dmenu -i -lines "${menu_nrows}" -p "${ROFI_PROMPT_TEXT}" "${ROFI_THEME[@]}")

# Execute rofi and get selection
selection="$(printf '%s\n' "${!menu[@]}" | sort | rofi "${rofi_options[@]}")"

# Directly execute the selected command if a selection was made and is not empty
if [[ -n "${selection}" ]]; then
  i3-msg -q "exec --no-startup-id ${menu[${selection}]}"
fi
