#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

# current_profile=$(/usr/bin/powerprofilesctl get)
# echo "$current_profile"

# current_profile=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor | uniq)
# echo "$current_profile"
current_profile=$(/usr/bin/powerprofilesctl get)

case "$current_profile" in
"performance")
    echo "<span color='#fe8019'></span> performance"
    ;;
"balanced")
    echo "<span color='#83a598'></span>  balanced"
    ;;
"power-saver")
    echo "<span color='#8ec07c'></span> power saver"
    ;;
*)
    echo "<span color='#fbf1c7'></span> unknown"
    ;;
esac
