#!/bin/sh

# Set keyboard layout to US,GR and map Caps to Escape
setxkbmap -layout us,gr -option 'grp:alt_shift_toggle' -option 'ctrl:nocaps'

# Map Escape to Left Control when pressed with a combination key
xcape -e Control_L=Escape
