---
pacman_packages:
  - ruby
  - go
  - nodejs
  - npm
  - lshw
  - bind
  - ntfs-3g
  - plocate
  - smartmontools
  - inetutils # provides 'hostname' used in scripts
  - diff-so-fancy # used by git: g df
  - bash-completion
  - stow
  - tldr
  - step-cli
  - mkcert
  - borg
  - zip
  - unzip
  - 7zip
  - xorg-server
  - xorg-xinit
  - xorg-xauth
  - xorg-xkill
  - xorg-xset
  - mesa
  - i3-wm
  - i3blocks
  - i3lock
  - xss-lock
  - wezterm
  - alacritty
  - picom
  - polybar
  - rofi
  - dunst
  - pango
  - ttf-cascadia-mono-nerd
  - ttf-cascadia-code-nerd
  - ttf-font-awesome
  - ttf-jetbrains-mono-nerd
  - noto-fonts
  - noto-fonts-emoji
  - noto-fonts-extra
  - lxappearance
  - thunar
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - thunar-volman
  - nautilus
  - seahorse
  - seahorse-nautilus
  - sushi
  - nautilus-share
  - nautilus-image-converter
  - yazi
  - poppler
  - ueberzugpp
  - obsidian
  - firefox
  - arandr
  - libnotify
  - xsettingsd
  - polkit-gnome
  - nitrogen
  - feh
  - numlockx
  - openvpn
  - network-manager-applet
  - networkmanager-openvpn
  - nm-connection-editor
  - wireguard-tools
  - solaar
  - easyeffects
  - calf
  - lsp-plugins-lv2
  - zam-plugins-lv2
  - mda.lv2
  - alsa-utils
  - playerctl
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - gst-plugin-pipewire
  - libpulse
  - wireplumber
  - sof-firmware
  - imagemagick
  - scrot
  - flameshot
  - jq
  - python-pipx
  - python-pip
  - python-i3ipc
  - python-pyfuse3 # required by borg, to mount borg repos
  - bat
  - maim
  - xdotool
  - xorg-xrandr
  - xorg-xinput
  - docker
  - docker-buildx
  - docker-compose
  - pigz
  - the_silver_searcher
  - ripgrep
  - gsettings-desktop-schemas
  - sops
  - fastfetch
  - xcape
  - gnome-calculator
  - gnome-calendar
  - gnome-text-editor
  - gnome-keyring
  - gnome-online-accounts
  - gnome-control-center
  - hunspell
  - hunspell-en_us
  - hunspell-el
  - xclip
  - mpv
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-utils
  - xdg-user-dirs
  - power-profiles-daemon
  - wireless_tools
  - iwd
  - bluez
  - bluez-utils
  - blueman
  - zsh
  - zsh-completions
  - fzf
  - starship
  - zoxide
  - eza
  - mise
  - fd
  - zellij
  - lazygit
  - cups
  - cups-filters
  - cups-pdf
  - system-config-printer
  - hplip
  - btop
  - htop
  - tree
  - gum
  - figlet
  - sddm
  - qt5-quickcontrols2
  - qt5-graphicaleffects
  - qt5-svg
  - brightnessctl
  - gtk4
  - libadwaita
  - fuse2
  - flatpak
  - imv
  - ffmpegthumbnailer
  - loupe
  - xorg-xbacklight
  - redshift
  - avahi
  - pacman-contrib
  - libreoffice-fresh
  - libreoffice-fresh-el
  - gvfs-goa
  - gvfs-google
  - gvfs-smb
  - gvfs-nfs
  - gvfs-afc
  - gvfs-dnssd
  - gvfs-wsdd
  - duf
  - usage # required by mise, for completions to work
  - evolution
  - mysql-workbench

# GPU packages for bare metal systems (have only AMD GPUs)
gpu_packages_baremetal:
  - xf86-video-amdgpu
  - vulkan-radeon
  - lib32-mesa
  - lib32-vulkan-radeon
  - corectrl
  - nvtop

# GPU packages for KVM/QEMU virtual machines
gpu_packages_vm_kvm:
  - xf86-video-qxl

# GPU packages for VirtualBox and VMware virtual machines
# Both use the same xf86-video-vmware driver since VirtualBox's VMSVGA emulates VMware SVGA
gpu_packages_vm_vmware_compatible:
  - xf86-video-vmware

chaotic_aur_enabled: true

chaotic_aur_packages:
  - yaru-gtk-theme
  - yaru-icon-theme
  - google-chrome
  - brave-bin
  - neovim-remote
  - visual-studio-code-bin
  - lazydocker
  - 1password
  - rofi-greenclip
  - synology-drive
  - nautilus-open-any-terminal
  - resvg
  - update-grub
  - btrfs-desktop-notification
  - btrfs-assistant
  - mysql-clients
  - libmysqlclient

aur_packages:
  - windsurf
  - cursor-extracted
  - caffeine-ng
  - 1password-cli
  - xkblayout-state-git
  - checkupdates-with-aur
  - vagrant

services:
  - NetworkManager
  - sshd
  - fstrim.timer
  - reflector.timer
  - docker
  - bluetooth
  - cups
  - sddm
  - avahi-daemon
  - systemd-timesyncd
  - power-profiles-daemon
  - paccache.timer

user_groups:
  - docker
