---
pacman_packages:
  - base-devel
  - git
  - man-db
  - man-pages
  - bash-completion
  - stow
  - tldr
  - step-cli
  - borg
  - wget
  - zip
  - unzip
  - 7zip
  - rsync
  - i3-wm
  - i3blocks
  - i3lock
  - xss-lock
  - wezterm
  - alacritty
  - picom
  - polybar
  - rofi
  - dunst
  - pango
  - ttf-cascadia-mono-nerd
  - ttf-cascadia-code-nerd
  - ttf-font-awesome
  - ttf-jetbrains-mono-nerd
  - noto-fonts
  - noto-fonts-emoji
  - noto-fonts-extra
  - lxappearance
  - thunar
  - thunar-archive-plugin
  - thunar-media-tags-plugin
  - thunar-volman
  - nautilus
  - seahorse
  - seahorse-nautilus
  - sushi
  - nautilus-share
  - nautilus-image-converter
  - yazi
  - poppler
  - ueberzugpp
  - obsidian
  - neovim
  - firefox
  - arandr
  - libnotify
  - xorg-xkill
  - xsettingsd
  - polkit-gnome
  - nitrogen
  - feh
  - xorg-xset
  - numlockx
  - networkmanager
  - network-manager-applet
  - nm-connection-editor
  - solaar
  - easyeffects
  - calf
  - lsp-plugins-lv2
  - zam-plugins-lv2
  - mda.lv2
  - alsa-utils
  - playerctl
  - pavucontrol
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - gst-plugin-pipewire
  - libpulse
  - wireplumber
  - sof-firmware
  - imagemagick
  - scrot
  - flameshot
  - jq
  - wget
  - python
  - python-pipx
  - python-pip
  - python-i3ipc
  - bat
  - maim
  - xdotool
  - xorg-xrandr
  - docker
  - docker-buildx
  - pigz
  - the_silver_searcher
  - ripgrep
  - gsettings-desktop-schemas
  - sops
  - fastfetch
  - xcape
  - gnome-calculator
  - gnome-calendar
  - gnome-text-editor
  - gnome-boxes
  - gnome-keyring
  - hunspell
  - hunspell-en_us
  - hunspell-el
  - geary
  - xclip
  - mpv
  - xdg-desktop-portal
  - xdg-desktop-portal-gtk
  - xdg-utils
  - xdg-user-dirs
  - power-profiles-daemon
  - wireless_tools
  - iwd
  - wpa_supplicant
  - bluez
  - bluez-utils
  - blueman
  - zsh
  - zsh-completions
  - fzf
  - starship
  - zoxide
  - eza
  - mise
  - fd
  - zellij
  - lazygit
  - cups
  - cups-filters
  - cups-pdf
  - system-config-printer
  - hplip
  - virtualbox
  - virtualbox-host-dkms
  - virtualbox-guest-iso
  - btop
  - htop
  - nvtop
  - tree
  - gum
  - figlet
  - sddm
  - qt5-quickcontrols2
  - qt5-graphicaleffects
  - qt5-svg
  - fastfetch
  - brightnessctl
  - gtk4
  - libadwaita
  - fuse2
  - flatpak
  - gvfs
  - imv
  - ffmpegthumbnailer
  - loupe
  - xorg-xbacklight
  - redshift

aur_packages:
  - yaru-gtk-theme
  - yaru-icon-theme
  - google-chrome
  - brave-bin
  - neovim-remote
  - visual-studio-code-bin
  - cursor-extracted
  - caffeine-ng
  - lazydocker-bin
  - 1password
  - 1password-cli
  - rofi-greenclip
  - xkblayout-state-git
  - synology-drive
  - checkupdates-with-aur
  - nautilus-open-any-terminal
  - resvg
