# Performance Metrics
fps
frame_timing=1
frametime
cpu_stats
cpu_temp
gpu_stats
gpu_temp
gpu_core_clock
vram
ram

# Visuals
table_columns=3
background_alpha=0.4
font_size=24
position=top-left

# Logic
toggle_hud=Shift_R+F7

### Set the FPS limits (0 means unlimited)
fps_limit=117,60,0

### Set the toggle hotkey (Default is Left Shift + F1)
toggle_fps_limit=Shift_L+F7

### Show the limit in the HUD so you know which one is active
show_fps_limit
