# catppuccin-latte.sh
# Catppuccin Latte theme color definitions
# https://github.com/catppuccin/catppuccin

export THEME_MODE="light"
export THEME_NAME="catppuccin-latte"
export THEME_DISPLAY_NAME="Catppuccin Latte"

# --- Base Colors ---
export CATPPUCCIN_LATTE_ROSEWATER="#dc8a78"
export CATPPUCCIN_LATTE_FLAMINGO="#dd7878"
export CATPPUCCIN_LATTE_PINK="#ea76cb"
export CATPPUCCIN_LATTE_MAUVE="#8839ef"
export CATPPUCCIN_LATTE_RED="#d20f39"
export CATPPUCCIN_LATTE_MAROON="#e64553"
export CATPPUCCIN_LATTE_PEACH="#fe640b"
export CATPPUCCIN_LATTE_YELLOW="#df8e1d"
export CATPPUCCIN_LATTE_GREEN="#40a02b"
export CATPPUCCIN_LATTE_TEAL="#179299"
export CATPPUCCIN_LATTE_SKY="#04a5e5"
export CATPPUCCIN_LATTE_SAPPHIRE="#209fb5"
export CATPPUCCIN_LATTE_BLUE="#1e66f5"
export CATPPUCCIN_LATTE_LAVENDER="#7287fd"
export CATPPUCCIN_LATTE_TEXT="#4c4f69"
export CATPPUCCIN_LATTE_SUBTEXT0="#6c6f85"
export CATPPUCCIN_LATTE_SUBTEXT1="#5c5f77"
export CATPPUCCIN_LATTE_OVERLAY0="#9ca0b0"
export CATPPUCCIN_LATTE_OVERLAY1="#8c8fa1"
export CATPPUCCIN_LATTE_OVERLAY2="#7c7f93"
export CATPPUCCIN_LATTE_SURFACE0="#ccd0da"
export CATPPUCCIN_LATTE_SURFACE1="#bcc0cc"
export CATPPUCCIN_LATTE_SURFACE2="#acb0be"
export CATPPUCCIN_LATTE_BASE="#eff1f5"
export CATPPUCCIN_LATTE_MANTLE="#e6e9ef"
export CATPPUCCIN_LATTE_CRUST="#dce0e8"

############ General ############
export THEME_SUCCESS="${CATPPUCCIN_LATTE_TEAL}"
export THEME_WARNING="${CATPPUCCIN_LATTE_YELLOW}"
export THEME_ALERT="${CATPPUCCIN_LATTE_RED}"

export THEME_EFFICIENT="${CATPPUCCIN_LATTE_GREEN}"
export THEME_BALANCED="${CATPPUCCIN_LATTE_LAVENDER}"
export THEME_PERFORMANCE="${CATPPUCCIN_LATTE_ROSEWATER}"

export THEME_COLD="${CATPPUCCIN_LATTE_BLUE}"
export THEME_NORMAL="${CATPPUCCIN_LATTE_TEAL}"
export THEME_HOT="${CATPPUCCIN_LATTE_YELLOW}"
export THEME_VERY_HOT="${CATPPUCCIN_LATTE_PEACH}"

################ i3 ################
# --- Client Colors ---
# border background text indicator child_border
export I3_CLIENT_FOCUSED_BORDER="${CATPPUCCIN_LATTE_MAUVE}"
export I3_CLIENT_FOCUSED_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_CLIENT_FOCUSED_TEXT="${CATPPUCCIN_LATTE_TEXT}"
export I3_CLIENT_FOCUSED_INDICATOR="${CATPPUCCIN_LATTE_ROSEWATER}"
export I3_CLIENT_FOCUSED_CHILD_BORDER="${CATPPUCCIN_LATTE_MAUVE}"

export I3_CLIENT_FOCUSED_INACTIVE_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"
export I3_CLIENT_FOCUSED_INACTIVE_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_CLIENT_FOCUSED_INACTIVE_TEXT="${CATPPUCCIN_LATTE_TEXT}"
export I3_CLIENT_FOCUSED_INACTIVE_INDICATOR="${CATPPUCCIN_LATTE_ROSEWATER}"
export I3_CLIENT_FOCUSED_INACTIVE_CHILD_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"

export I3_CLIENT_UNFOCUSED_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"
export I3_CLIENT_UNFOCUSED_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_CLIENT_UNFOCUSED_TEXT="${CATPPUCCIN_LATTE_TEXT}"
export I3_CLIENT_UNFOCUSED_INDICATOR="${CATPPUCCIN_LATTE_ROSEWATER}"
export I3_CLIENT_UNFOCUSED_CHILD_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"

export I3_CLIENT_URGENT_BORDER="${CATPPUCCIN_LATTE_PEACH}"
export I3_CLIENT_URGENT_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_CLIENT_URGENT_TEXT="${CATPPUCCIN_LATTE_PEACH}"
export I3_CLIENT_URGENT_INDICATOR="${CATPPUCCIN_LATTE_OVERLAY0}"
export I3_CLIENT_URGENT_CHILD_BORDER="${CATPPUCCIN_LATTE_PEACH}"

export I3_CLIENT_PLACEHOLDER_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"
export I3_CLIENT_PLACEHOLDER_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_CLIENT_PLACEHOLDER_TEXT="${CATPPUCCIN_LATTE_TEXT}"
export I3_CLIENT_PLACEHOLDER_INDICATOR="${CATPPUCCIN_LATTE_OVERLAY0}"
export I3_CLIENT_PLACEHOLDER_CHILD_BORDER="${CATPPUCCIN_LATTE_OVERLAY0}"

export I3_CLIENT_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"

# --- Bar Colors ---
export I3_BAR_BACKGROUND="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_STATUSLINE="${CATPPUCCIN_LATTE_TEXT}"
export I3_BAR_SEPARATOR="${CATPPUCCIN_LATTE_OVERLAY1}"

# border background text
export I3_BAR_FOCUSED_WORKSPACE_BORDER="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_FOCUSED_WORKSPACE_BG="${CATPPUCCIN_LATTE_MAUVE}"
export I3_BAR_FOCUSED_WORKSPACE_TEXT="${CATPPUCCIN_LATTE_CRUST}"

export I3_BAR_ACTIVE_WORKSPACE_BORDER="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_ACTIVE_WORKSPACE_BG="${CATPPUCCIN_LATTE_SURFACE2}"
export I3_BAR_ACTIVE_WORKSPACE_TEXT="${CATPPUCCIN_LATTE_TEXT}"

export I3_BAR_INACTIVE_WORKSPACE_BORDER="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_INACTIVE_WORKSPACE_BG="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_INACTIVE_WORKSPACE_TEXT="${CATPPUCCIN_LATTE_TEXT}"

export I3_BAR_BINDING_MODE_BORDER="${CATPPUCCIN_LATTE_ROSEWATER}"
export I3_BAR_BINDING_MODE_BG="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_BINDING_MODE_TEXT="${CATPPUCCIN_LATTE_TEXT}"

export I3_BAR_URGENT_WORKSPACE_BORDER="${CATPPUCCIN_LATTE_BASE}"
export I3_BAR_URGENT_WORKSPACE_BG="${CATPPUCCIN_LATTE_RED}"
export I3_BAR_URGENT_WORKSPACE_TEXT="${CATPPUCCIN_LATTE_CRUST}"

################ polybar ################
export POLYBAR_BG="${CATPPUCCIN_LATTE_BASE}"
export POLYBAR_FG="${CATPPUCCIN_LATTE_TEXT}"
export POLYBAR_FG_MUTED="${CATPPUCCIN_LATTE_SUBTEXT1}"
export POLYBAR_FG_LIGHT="${CATPPUCCIN_LATTE_BASE}"
export POLYBAR_PRIMARY="${CATPPUCCIN_LATTE_LAVENDER}"
export POLYBAR_FOCUS="${CATPPUCCIN_LATTE_MAUVE}"
export POLYBAR_SUCCESS="${THEME_SUCCESS}"
export POLYBAR_WARNING="${THEME_WARNING}"
export POLYBAR_ALERT="${THEME_ALERT}"
export POLYBAR_DISABLED="${CATPPUCCIN_LATTE_SUBTEXT0}"
export POLYBAR_SEPARATOR="${CATPPUCCIN_LATTE_OVERLAY1}"
export POLYBAR_ACCENT="${CATPPUCCIN_LATTE_SKY}"

### BAT
export BAT_THEME="Catppuccin Latte"

### ALACRITTY
export ALACRITTY_THEME="catppuccin-latte"

### DUNST
export DUNST_ICON_PATH="${HOME}/.config/dunst/icons/${THEME_NAME}"

export DUNST_LOW_BACKGROUND="${CATPPUCCIN_LATTE_LAVENDER}"
export DUNST_LOW_FOREGROUND="${CATPPUCCIN_LATTE_BASE}"
export DUNST_LOW_FRAME_COLOR="${CATPPUCCIN_LATTE_BLUE}"
export DUNST_LOW_ICON="bell-regular-base"

export DUNST_NORMAL_BACKGROUND="${CATPPUCCIN_LATTE_LAVENDER}"
export DUNST_NORMAL_FOREGROUND="${CATPPUCCIN_LATTE_BASE}"
export DUNST_NORMAL_FRAME_COLOR="${CATPPUCCIN_LATTE_BLUE}"
export DUNST_NORMAL_ICON="bell-regular-base"

export DUNST_CRITICAL_BACKGROUND="${CATPPUCCIN_LATTE_MAROON}"
export DUNST_CRITICAL_FOREGROUND="${CATPPUCCIN_LATTE_BASE}"
export DUNST_CRITICAL_FRAME_COLOR="${CATPPUCCIN_LATTE_RED}"
export DUNST_CRITICAL_ICON="triangle-exclamation-solid-base"

### Rofi
export ROFI_BASE="${CATPPUCCIN_LATTE_BASE}"
export ROFI_TEXT="${CATPPUCCIN_LATTE_TEXT}"
export ROFI_RED="${CATPPUCCIN_LATTE_RED}"
export ROFI_LIGHTBG="${CATPPUCCIN_LATTE_MANTLE}"
export ROFI_LIGHTFG="${CATPPUCCIN_LATTE_TEXT}"
export ROFI_ACTIVE_FOREGROUND="${CATPPUCCIN_LATTE_BLUE}"
export ROFI_SELECTED_ACTIVE_BACKGROUND="${CATPPUCCIN_LATTE_BLUE}"
export ROFI_ALTERNATE_ACTIVE_FOREGROUND="${CATPPUCCIN_LATTE_BLUE}"
