---
- name: Set timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link
    force: true

- name: Sync the hardware clock with the system time
  ansible.builtin.command: hwclock --systohc
  changed_when: false

- name: Enable NTP
  ansible.builtin.command: timedatectl set-ntp true
  changed_when: false

- name: Enable locales
  ansible.builtin.replace:
    path: /etc/locale.gen
    regexp: "^#{{ item }} UTF-8"
    replace: "{{ item }} UTF-8"
  loop: "{{ locales }}"

- name: Generate locale
  ansible.builtin.command: locale-gen
  changed_when: false

- name: Create locale.conf and set default locale
  ansible.builtin.copy:
    dest: /etc/locale.conf
    content: "LANG={{ default_locale }}"
    mode: "0644"

- name: Create vconsole.conf
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    content: |
      KEYMAP=us
      KEYMAP_TOGGLE=gr
      FONT={{ console_font }}
    mode: "0644"

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Create hostname file
  ansible.builtin.copy:
    dest: /etc/hostname
    content: "{{ hostname }}"
    mode: "0644"

- name: Add hostname to /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1"
    line: "127.0.1.1 {{ hostname }}.localdomain {{ hostname }}"
    state: present

- name: Set default editor
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^EDITOR="
    line: "EDITOR=nvim"
    state: present

- name: Set default visual editor
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "^VISUAL="
    line: "VISUAL=nvim"
    state: present

- name: Use F1-F12 without Fn key
  ansible.builtin.copy:
    src: hid_apple.conf
    dest: /etc/modprobe.d/hid_apple.conf
    mode: "0644"
    owner: root
    group: root

- name: Set vm.swappiness to 10
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
    state: present
    sysctl_file: /etc/sysctl.d/99-vm.conf
