# gruvbox-dark.sh
# Gruvbox theme color definitions
# https://github.com/morhetz/gruvbox

export THEME_MODE="dark"
export THEME_NAME="gruvbox-dark"
export THEME_DISPLAY_NAME="Gruvbox Dark"

# --- Base Colors ---
export GRUVBOX_DARK_BG='#282828'
export GRUVBOX_DARK_BG_TRANSPARENT='#cc282828'
export GRUVBOX_DARK_BG0='#282828'
export GRUVBOX_DARK_BG0_HARD='#1d2021'
export GRUVBOX_DARK_BG0_SOFT='#32302f'
export GRUVBOX_DARK_BG1='#3c3836'
export GRUVBOX_DARK_BG2='#504945'
export GRUVBOX_DARK_BG3='#665c54'
export GRUVBOX_DARK_BG4='#7c6f64'
export GRUVBOX_DARK_FG='#ebdbb2'
export GRUVBOX_DARK_FG0='#fbf1c7'
export GRUVBOX_DARK_FG1='#ebdbb2'
export GRUVBOX_DARK_FG2='#d5c4a1'
export GRUVBOX_DARK_FG3='#bdae93'
export GRUVBOX_DARK_FG4='#a89984'
export GRUVBOX_DARK_GRAY='#928374'
export GRUVBOX_DARK_GRAY_LIGHT='#a89984'
export GRUVBOX_DARK_RED='#cc241d'
export GRUVBOX_DARK_RED_LIGHT='#fb4934'
export GRUVBOX_DARK_GREEN='#98971a'
export GRUVBOX_DARK_GREEN_LIGHT='#b8bb26'
export GRUVBOX_DARK_YELLOW='#d79921'
export GRUVBOX_DARK_YELLOW_LIGHT='#fabd2f'
export GRUVBOX_DARK_ORANGE='#d65d0e'
export GRUVBOX_DARK_ORANGE_LIGHT='#fe8019'
export GRUVBOX_DARK_BLUE='#458588'
export GRUVBOX_DARK_BLUE_LIGHT='#83a598'
export GRUVBOX_DARK_PURPLE='#b16286'
export GRUVBOX_DARK_PURPLE_LIGHT='#d3869b'
export GRUVBOX_DARK_AQUA='#689d6a'
export GRUVBOX_DARK_AQUA_LIGHT='#8ec07c'

############ General ############
export THEME_SUCCESS="${GRUVBOX_DARK_GREEN}"
export THEME_WARNING="${GRUVBOX_DARK_ORANGE}"
export THEME_ALERT="${GRUVBOX_DARK_RED}"

export THEME_EFFICIENT="${GRUVBOX_DARK_AQUA}"
export THEME_BALANCED="${GRUVBOX_DARK_YELLOW}"
export THEME_PERFORMANCE="${GRUVBOX_DARK_ORANGE_LIGHT}"

export THEME_COLD="${GRUVBOX_DARK_BLUE_LIGHT}"
export THEME_NORMAL="${GRUVBOX_DARK_GREEN_LIGHT}"
export THEME_HOT="${GRUVBOX_DARK_YELLOW_LIGHT}"
export THEME_VERY_HOT="${GRUVBOX_DARK_ORANGE_LIGHT}"

################ i3 #################
# --- Client Colors ---
# border background text indicator child_border
export I3_CLIENT_FOCUSED_BORDER="${GRUVBOX_DARK_AQUA}"
export I3_CLIENT_FOCUSED_BACKGROUND="${GRUVBOX_DARK_AQUA}"
export I3_CLIENT_FOCUSED_TEXT="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_FOCUSED_INDICATOR="${GRUVBOX_DARK_PURPLE}"
export I3_CLIENT_FOCUSED_CHILD_BORDER="${GRUVBOX_DARK_AQUA}"

export I3_CLIENT_FOCUSED_INACTIVE_BORDER="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_FOCUSED_INACTIVE_BACKGROUND="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_FOCUSED_INACTIVE_TEXT="${GRUVBOX_DARK_YELLOW}"
export I3_CLIENT_FOCUSED_INACTIVE_INDICATOR="${GRUVBOX_DARK_PURPLE}"
export I3_CLIENT_FOCUSED_INACTIVE_CHILD_BORDER="${GRUVBOX_DARK_BG0_HARD}"

export I3_CLIENT_UNFOCUSED_BORDER="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_UNFOCUSED_BACKGROUND="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_UNFOCUSED_TEXT="${GRUVBOX_DARK_YELLOW}"
export I3_CLIENT_UNFOCUSED_INDICATOR="${GRUVBOX_DARK_PURPLE}"
export I3_CLIENT_UNFOCUSED_CHILD_BORDER="${GRUVBOX_DARK_BG0_HARD}"

export I3_CLIENT_URGENT_BORDER="${GRUVBOX_DARK_RED}"
export I3_CLIENT_URGENT_BACKGROUND="${GRUVBOX_DARK_RED}"
export I3_CLIENT_URGENT_TEXT="${GRUVBOX_DARK_FG0}"
export I3_CLIENT_URGENT_INDICATOR="${GRUVBOX_DARK_RED}"
export I3_CLIENT_URGENT_CHILD_BORDER="${GRUVBOX_DARK_RED}"

export I3_CLIENT_PLACEHOLDER_BORDER="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_PLACEHOLDER_BACKGROUND="${GRUVBOX_DARK_BG}"
export I3_CLIENT_PLACEHOLDER_TEXT="${GRUVBOX_DARK_FG0}"
export I3_CLIENT_PLACEHOLDER_INDICATOR="${GRUVBOX_DARK_BG0_HARD}"
export I3_CLIENT_PLACEHOLDER_CHILD_BORDER="${GRUVBOX_DARK_BG0_HARD}"

export I3_CLIENT_BACKGROUND="${GRUVBOX_DARK_BG2}"

# --- Bar Colors ---
export I3_BAR_BACKGROUND="${GRUVBOX_DARK_BG}"
export I3_BAR_STATUSLINE="${GRUVBOX_DARK_FG2}"
export I3_BAR_SEPARATOR="${GRUVBOX_DARK_BG2}"

# border background text
export I3_BAR_FOCUSED_WORKSPACE_BORDER="${GRUVBOX_DARK_AQUA}"
export I3_BAR_FOCUSED_WORKSPACE_BG="${GRUVBOX_DARK_AQUA}"
export I3_BAR_FOCUSED_WORKSPACE_TEXT="${GRUVBOX_DARK_BG0_HARD}"

export I3_BAR_ACTIVE_WORKSPACE_BORDER="${GRUVBOX_DARK_BG0_HARD}"
export I3_BAR_ACTIVE_WORKSPACE_BG="${GRUVBOX_DARK_GRAY_LIGHT}"
export I3_BAR_ACTIVE_WORKSPACE_TEXT="${GRUVBOX_DARK_BG}"

export I3_BAR_INACTIVE_WORKSPACE_BORDER="${GRUVBOX_DARK_BG0_HARD}"
export I3_BAR_INACTIVE_WORKSPACE_BG="${GRUVBOX_DARK_BG0_HARD}"
export I3_BAR_INACTIVE_WORKSPACE_TEXT="${GRUVBOX_DARK_FG3}"

export I3_BAR_BINDING_MODE_BORDER="${GRUVBOX_DARK_ORANGE}"
export I3_BAR_BINDING_MODE_BG="${GRUVBOX_DARK_BG3}"
export I3_BAR_BINDING_MODE_TEXT="${GRUVBOX_DARK_FG0}"

export I3_BAR_URGENT_WORKSPACE_BORDER="${GRUVBOX_DARK_RED}"
export I3_BAR_URGENT_WORKSPACE_BG="${GRUVBOX_DARK_RED_LIGHT}"
export I3_BAR_URGENT_WORKSPACE_TEXT="${GRUVBOX_DARK_BG}"

############# polybar #############
export POLYBAR_BG="${GRUVBOX_DARK_BG_TRANSPARENT}"
export POLYBAR_FG="${GRUVBOX_DARK_FG}"
export POLYBAR_FG_MUTED="${GRUVBOX_DARK_FG3}"
export POLYBAR_FG_LIGHT="${GRUVBOX_DARK_FG0}"
export POLYBAR_PRIMARY="${GRUVBOX_DARK_YELLOW}"
export POLYBAR_FOCUS="${GRUVBOX_DARK_AQUA}"
export POLYBAR_SUCCESS="${GRUVBOX_DARK_GREEN}"
export POLYBAR_WARNING="${GRUVBOX_DARK_ORANGE}"
export POLYBAR_ALERT="${GRUVBOX_DARK_RED}"
export POLYBAR_DISABLED="${GRUVBOX_DARK_GRAY_LIGHT}"
export POLYBAR_SEPARATOR="${GRUVBOX_DARK_BG4}"
export POLYBAR_ACCENT="${GRUVBOX_DARK_PURPLE}"

### BAT
export BAT_THEME="gruvbox-dark"

### ALACRITTY
export ALACRITTY_THEME="gruvbox-dark"

### DUNST
export DUNST_ICON_PATH="${HOME}/.config/dunst/icons/${THEME_NAME}"

export DUNST_LOW_BACKGROUND="${GRUVBOX_DARK_BLUE}"
export DUNST_LOW_FOREGROUND="${GRUVBOX_DARK_FG0}"
export DUNST_LOW_FRAME_COLOR="${GRUVBOX_DARK_BLUE_LIGHT}"
export DUNST_LOW_ICON="bell-regular-fg"

export DUNST_NORMAL_BACKGROUND="${GRUVBOX_DARK_BLUE}"
export DUNST_NORMAL_FOREGROUND="${GRUVBOX_DARK_FG0}"
export DUNST_NORMAL_FRAME_COLOR="${GRUVBOX_DARK_BLUE_LIGHT}"
export DUNST_NORMAL_ICON="bell-regular-fg0"

export DUNST_CRITICAL_BACKGROUND="${GRUVBOX_DARK_RED}"
export DUNST_CRITICAL_FOREGROUND="${GRUVBOX_DARK_FG0}"
export DUNST_CRITICAL_FRAME_COLOR="${GRUVBOX_DARK_RED_LIGHT}"
export DUNST_CRITICAL_ICON="triangle-exclamation-solid-fg0"

### Rofi
export ROFI_BASE="${GRUVBOX_DARK_BG}"
export ROFI_TEXT="${GRUVBOX_DARK_FG}"
export ROFI_RED="${GRUVBOX_DARK_RED}"
export ROFI_LIGHTBG="${GRUVBOX_DARK_BG1}"
export ROFI_LIGHTFG="${GRUVBOX_DARK_FG}"
export ROFI_ACTIVE_FOREGROUND="${GRUVBOX_DARK_YELLOW}"
export ROFI_SELECTED_ACTIVE_BACKGROUND="${GRUVBOX_DARK_YELLOW}"
export ROFI_ALTERNATE_ACTIVE_FOREGROUND="${GRUVBOX_DARK_YELLOW}"

### Zellij
export ZELLIJ_THEME="gruvbox-dark"
