---
- name: Post-Install Configuration
  hosts: localhost
  become: true
  connection: local

  vars:
    username: "{{ ansible_env.SUDO_USER }}"

  roles:
    - role: snapshots
      tags: ["snapshots"]
    - role: network
      tags: ["network"]
    - role: thinkpad
      tags: ["thinkpad"]
