---
# Boot configuration defaults
enable_encryption: false
encrypted_device: "" # Device path (e.g., /dev/sda1) - UUID will be automatically detected
encryption_password: ""

# GRUB configuration
grub_timeout: 5
grub_default: 2 # Third entry (regular linux kernel when submenus are disabled)
grub_disable_submenu: true # Show all kernels in main menu, regular linux appears third
# PCIe power management disabled to fix Intel I225-V Ethernet disconnection issues
grub_cmdline_linux_default: "nowatchdog loglevel=3 quiet pcie_port_pm=off pcie_aspm.policy=performance"
grub_preload_modules: "part_gpt part_msdos btrfs"

# mkinitcpio configuration
mkinitcpio_modules: ["btrfs", "crc32c"]
mkinitcpio_binaries: []
mkinitcpio_files: []
mkinitcpio_hooks_encrypted: "base udev autodetect microcode modconf kms keyboard keymap consolefont block encrypt filesystems fsck grub-btrfs-overlayfs"
mkinitcpio_hooks_normal: "base udev autodetect microcode modconf kms keyboard keymap consolefont block filesystems fsck grub-btrfs-overlayfs"
